### ISSUE TITLE
Add issue and return forms

### ISSUE THREAD

**Issue by boddolk** [boddolk/LibraryManager#38]
## Tasks description

- Add issue form and it's elements.
- Add return form and it's elements.

## Tasks

- [x] Create issue form;
- [ ] Add main elements for issue form;
- [x] Create return form;
- [ ] Add main elements for return form.
