### ISSUE TITLE
Add a hierarchy of user classes

### ISSUE THREAD

**Issue by boddolk** [boddolk/LibraryManager#6]
## Tasks description

- Create an initial abstract class;
- Inherit the right classes to cover the needs of the application.

## Tasks

- [x]  Create base user class:
![Image](https://github.com/user-attachments/assets/67b769fd-86ab-4975-9b0f-0bcf5f7a073a)

- [x]  Create admin class:
![Image](https://github.com/user-attachments/assets/f1ab472e-5f37-4fc3-a5ba-3cc4340d87b4)

- [x]  Create visitor class:
![Image](https://github.com/user-attachments/assets/924bc116-4465-4723-af51-82158314172d)
