### ISSUE TITLE
Fix transitions between windows

### ISSUE THREAD

**Issue by boddolk** [boddolk/LibraryManager#70]
## Task description

- FIX THE PROBLEM WITH THE USER WINDOW LOOPING AFTER CLOSING THE HISTORY;
- Figure out how to extract information about the user;
- Determine the sequence of calling windows;
- Determine which ones should be hidden;
- Write down the general logic of their openings.

## Tasks

- [x] FIX HISTORY BUG;
- [x] Get information about the user;
- [x] The sequence of calling windows;
- [x] Hiding windows;
- [x] General logic of opening windows.
